runtime: nodejs20
env: standard
instance_class: F1
handlers:
  - url: /.*
    script: auto
  - url: .*
    script: auto
readiness_check:
  app_start_timeout_sec: 300 
  runtime: nodejs20
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
