runtime: php82  # version of php
env: standard     # set app engine env to standard
runtime_config:
  document_root: .
handlers:
  - url: /(.*\.(gif|png|jpg|css|js|json))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|css|js|json)$
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
PUSHER_APP_ID:
  PUSHER_APP_KEY:
  PUSHER_APP_SECRET:
  PUSHER_APP_CLUSTER: mt1 //the tmp folder is used for caching on GCP as opposed to the default storage folder
  APP_SERVICES_CACHE: /tmp/services.php
  APP_PACKAGES_CACHE: /tmp/packages.php
  APP_CONFIG_CACHE: /tmp/config.php
  APP_ROUTES_CACHE: /tmp/routes.php
